title: "Sample API with POST"
apiFirst: false
developerEmail: morozov@gmail.com
groupId: org.sample.webmvc
basePackage: org.sample.webmvc
apiPackage: org.sample.webmvc.api
invokerPackage: org.sample.webmvc.api
modelPackage: org.sample.webmvc.model
configPackage: org.sample.webmvc.configuration
useSpringBoot3: true
dateLibrary: java8
library: spring-boot
reactive: false
interfaceOnly: false
legacyDiscriminatorBehavior: false
oas3: true
performBeanValidation: true
useBeanValidation: true
skipDefaultInterface: true
useTags: false
