openapi: 3.0.3
info:
  title: Sample API Definition with GET and POST
  version: "1.0"
servers:
- url: /v1
- url: https://api.server.test/v1
paths:
  /test:
    get:
      operationId: testParametersVerification
      parameters:
      - description: Object ID as query parameter
        explode: true
        in: query
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/Id'
        style: form
      - explode: true
        in: query
        name: name
        required: true
        schema:
          $ref: '#/components/schemas/Name'
        style: form
      - explode: true
        in: query
        name: age
        required: true
        schema:
          $ref: '#/components/schemas/Age'
        style: form
      - explode: true
        in: query
        name: description
        required: false
        schema:
          $ref: '#/components/schemas/Description'
        style: form
      responses:
        "204":
          description: OK
      summary: a sample GET request with input passed as parameters
      x-accepts: application/json
    post:
      operationId: testBodyVerification
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestRequestBody'
        description: sample POST request body
        required: true
      responses:
        "204":
          description: OK
      summary: a sample POST request with a mandatory Request Body
      x-contentType: application/json
      x-accepts: application/json
components:
  schemas:
    Id:
      description: Object ID
      format: uuid
      type: string
    Name:
      description: Object Name
      minLength: 10
      type: string
    Age:
      description: Object Age
      maximum: 99
      minimum: 1
      type: integer
    Description:
      description: a lengthy Object Description
      minLength: 20
      type: string
    TestRequestBody:
      example:
        name: name
        description: description
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        age: 8
      properties:
        id:
          description: Object ID
          format: uuid
          type: string
        name:
          description: Object Name
          minLength: 10
          type: string
        age:
          description: Object Age
          maximum: 99
          minimum: 1
          type: integer
        description:
          description: a lengthy Object Description
          minLength: 20
          type: string
      required:
      - age
      - id
      - name
      type: object
